src/Entity/Cour.php
<?php

namespace App\Entity;

use App\Repository\CourRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CourRepository::class)]
class Cour
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(name: "id_cour")]
    private ?int $id = null;

    #[ORM\Column(length: 255, name: "Matiere")]
    #[Assert\NotBlank(message: "Le champ Matiere ne doit pas être vide.")]
    #[Assert\Regex(
        pattern: "/^[a-zA-Z\s]+$/",
        message: "Le champ Matiere ne doit contenir que des lettres et des espaces."
    )]
    private ?string $matiere = null;

    #[ORM\Column(type: 'datetime', name: "Date_Debut")]
    #[Assert\NotBlank(message: "Veuillez sélectionner une date de début.")]
    private ?\DateTimeInterface $dateDebut = null;

    #[ORM\Column(type: 'datetime', name: "Date_Fin")]
    #[Assert\NotBlank(message: "Veuillez sélectionner une date de fin.")]
    #[Assert\GreaterThan(
        propertyPath: "dateDebut",
        message: "La date de fin doit être postérieure à la date de début."
    )]
    private ?\DateTimeInterface $dateFin = null;

    #[ORM\OneToMany(mappedBy: 'id_cour', targetEntity: Unite::class)]
    private Collection $unites;

    public function __construct()
    {
        $this->unites = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMatiere(): ?string
    {
        return $this->matiere;
    }

    public function setMatiere(string $matiere): self
    {
        $this->matiere = $matiere;
        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(\DateTimeInterface $dateDebut): self
    {
        $this->dateDebut = $dateDebut;
        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->dateFin;
    }

    public function setDateFin(\DateTimeInterface $dateFin): self
    {
        $this->dateFin = $dateFin;
        return $this;
    }
        /**
     * @return Collection<int, Unite>
     */
    public function getUnites(): Collection
    {
        return $this->unites;
    }
    public function addUnite(Unite $unite): self
    {
        if (!$this->unites->contains($unite)) {
            $this->unites->add($unite);
            $unite->setIdCour($this);
        }
        return $this;
    }
   
    public function __toString(): string
    {
        if ($this->unites === null) {
            return '';
        }
        return $this->getMatiere(); // ou toute autre propriété que vous souhaitez utiliser comme représentation
    }

   
    public function removeUnite(Unite $unite): static
    {
        if ($this->unites->removeElement($unite)) {
            // set the owning side to null (unless already changed)
            if ($unite->getIdCour() === $this) {
                $unite->setIdCour(null);
            }
        }
        return $this;
    }
 
}

src/Entity/Unite.php
<?php

namespace App\Entity;

use App\Repository\UniteRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UniteRepository::class)]
class Unite
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(name: "id", type: "integer")]
    private ?int $id = null;

    #[ORM\Column(name: "num_unite", type: "integer")]
    private ?int $NumUnite = null;

    #[ORM\Column(length: 255, name: "Titre")]
    #[Assert\NotBlank(message: "Le champ Titre ne peut pas être vide.")]
    private ?string $Titre = null;

    #[ORM\Column(length: 11, name: "Statut")]
    #[Assert\NotBlank(message: "Le champ Statut ne peut pas être vide.")]
    private ?string $Statut = null;

    #[ORM\Column(length: 255, name: "Contenu")]
    #[Assert\NotBlank(message: "Le champ Contenu ne peut pas être vide.")]
    private ?string $Contenu = null;

    #[ORM\Column(name: "dateDepot", type: "datetime", options: ["default" => "CURRENT_TIMESTAMP"])]
    private ?\DateTimeInterface $dateDepot = null;

    #[ORM\ManyToOne(targetEntity: Cour::class, inversedBy: 'unites')]
    #[ORM\JoinColumn(name: "id_cour", referencedColumnName: "id_cour", nullable: false)]
    private ?Cour $id_cour = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumUnite(): ?int
    {
        return $this->NumUnite;
    }

    public function setNumUnite(int $NumUnite): self
    {
        $this->NumUnite = $NumUnite;
        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;
        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->Statut;
    }

    public function setStatut(string $Statut): self
    {
        $this->Statut = $Statut;
        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->Contenu;
    }

    public function setContenu(string $Contenu): self
    {
        $this->Contenu = $Contenu;
        return $this;
    }

    public function getDateDepot(): ?\DateTimeInterface
    {
        return $this->dateDepot;
    }

    public function setDateDepot(\DateTimeInterface $dateDepot): self
    {
        $this->dateDepot = $dateDepot;
        return $this;
    }

    public function getIdCour(): ?Cour
    {
        return $this->id_cour;
    }

    public function setIdCour(?Cour $id_cour): self
    {
        $this->id_cour = $id_cour;
        return $this;
    }
}

src/Controller/CourController.php
<?php

namespace App\Controller;

use App\Entity\Cour;
use App\Entity\Unite;
use App\Form\UniteType;
use App\Form\Cour1Type;
use App\Repository\CourRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\TwilioService;


#[Route('/cour')]
class CourController extends AbstractController
{
    #[Route('/', name: 'app_cour_index', methods: ['GET'])]
    public function index(Request $request, CourRepository $courRepository): Response
    {
        $search = $request->query->get('search');
        $sort = $request->query->get('sort');

        // Récupérer les cours en fonction de la recherche et du tri
        $cours = $courRepository->findBySearchAndSort($search, $sort);

        return $this->render('cour/index.html.twig', [
            'cours' => $cours,
        ]);
    }

    #[Route('/new', name: 'app_cour_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, TwilioService $twilioService): Response
    {
        $cour = new Cour();
        $form = $this->createForm(Cour1Type::class, $cour);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($cour);
            $entityManager->flush();
    
            // Envoie un SMS après l'ajout du cours
            $message = 'Nouveau cours ajouté : ' . $cour->getMatiere();
            try {
                $twilioService->sendSms('+21629082917', $message);
            } catch (\Exception $e) {
                // Gérer l'erreur ici
                $this->addFlash('error', 'Erreur lors de l\'envoi du SMS : ' . $e->getMessage());
            }
    
            $this->addFlash('success', 'Le cours a été ajouté avec succès.');
    
            return $this->redirectToRoute('app_cour_index', [], Response::HTTP_SEE_OTHER);
        }
    
        return $this->renderForm('cour/new.html.twig', [
            'cour' => $cour,
            'form' => $form,
        ]);
    }
    

    #[Route('/{id}', name: 'app_cour_show', methods: ['GET'])]
    public function show(Cour $cour, EntityManagerInterface $entityManager, $id): Response
    {
        $cour = $entityManager->getRepository(Cour::class)->find($id);

        return $this->render('cour/show.html.twig', [
            'cour' => $cour,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_cour_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Cour $cour, EntityManagerInterface $entityManager, $id): Response
    {
        $cour = $entityManager->getRepository(Cour::class)->find($id);

        $form = $this->createForm(Cour1Type::class, $cour);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_cour_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('cour/edit.html.twig', [
            'cour' => $cour,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_cour_delete', methods: ['POST'])]
    public function delete(Request $request, Cour $cour, EntityManagerInterface $entityManager, $id): Response
    {
        $cour = $entityManager->getRepository(Cour::class)->find($id);

        if ($this->isCsrfTokenValid('delete'.$cour->getId(), $request->request->get('_token'))) {
            $entityManager->remove($cour);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_cour_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}/new_unite', name: 'app_cour_new_unite', methods: ['GET', 'POST'])]
    public function newUnite(Request $request, Cour $cour, EntityManagerInterface $entityManager): Response
    {
        $unite = new Unite();
        $unite->setIdCour($cour); // Associer l'unité au cours actuel
        $form = $this->createForm(UniteType::class, $unite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($unite);
            $entityManager->flush();

            return $this->redirectToRoute('app_cour_units', ['id' => $cour->getId()]);
        }

        return $this->renderForm('cour/new_unite.html.twig', [
            'cour' => $cour,
            'form' => $form,
        ]);
    }

    
    #[Route('/{id}/units', name: 'app_cour_units', methods: ['GET'])]
    public function showUnits(Cour $cour, EntityManagerInterface $entityManager, $id): Response
    {
        $cour = $entityManager->getRepository(Cour::class)->find($id);

        // Récupérer les unités du cours spécifique
        $unites = $cour->getUnites();
    
        return $this->render('cour/units.html.twig', [
            'cour' => $cour,
            'unites' => $unites,
        ]);
    }

}

templates/cour/Modifier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un cours{% endblock %}

{% block body %}
    <div class="container mt-5">
        <h1 class="text-center mb-4">Modifier un cours</h1>

        {{ form_start(form) }}
        {{ form_row(form.Matiere) }}
        {# Ajoutez d'autres champs du formulaire selon votre type de formulaire CourType #}
        <div class="text-center">
            <button type="submit" class="add-course-btn">Modifier</button>
        </div>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/cour/_delete_form.html.twig
<style>
    /* Styles pour le bouton de suppression */
    .delete-course-btn {
        background-color: #dc3545; /* Rouge */
        color: #fff; /* Texte blanc */
        border: none;
        border-radius: 4px;
        padding: 10px 20px;
        font-size: 10px;
        cursor: pointer;
        transition: background-color 0.3s, transform 0.2s; /* Ajout de transition pour le changement de couleur et l'effet de survol */
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); /* Ajout d'une ombre pour un effet de profondeur */
    }

    .delete-course-btn:hover {
        background-color: #c82333; /* Rouge foncé au survol */
        transform: translateY(-5px); /* Légère translation vers le haut au survol */
    }

    .delete-course-btn:active {
        transform: translateY(3px); /* Légère translation vers le bas lorsqu'il est cliqué */
        box-shadow: none; /* Suppression de l'ombre lorsqu'il est cliqué */
    }
</style>


<form method="post" action="{{ path('app_cour_delete', {'id': cour.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ cour.id) }}">
    <button class="delete-course-btn">Delete</button>
</form>

templates/cour/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button type="submit" class="btn btn-info btn-sm">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/cour/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Cour{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/styles.css') }}">
    <style>
    /* Styles pour le bouton de suppression */
    .button-course-btn {
        background-color: #003399; /* Rouge */
        color: #fff; /* Texte blanc */
        border: none;
        border-radius: 4px;
        padding: 10px 20px;
        font-size: 10px;
        cursor: pointer;
        transition: background-color 0.3s, transform 0.2s; /* Ajout de transition pour le changement de couleur et l'effet de survol */
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); /* Ajout d'une ombre pour un effet de profondeur */
    }

    .button-course-btn:hover {
        background-color: #000099; /* Rouge foncé au survol */
        transform: translateY(-5px); /* Légère translation vers le haut au survol */
    }

    .button-course-btn:active {
        transform: translateY(3px); /* Légère translation vers le bas lorsqu'il est cliqué */
        box-shadow: none; /* Suppression de l'ombre lorsqu'il est cliqué */
    }
</style>

{% endblock %}

{% block body %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ block('title') }}</div>
                    <div class="card-body">
                        <h2 class="text-center mb-4">Edit Cour</h2>
                        {{ form_start(form) }}
                        <div class="form-group">
                            {{ form_label(form.Matiere) }}
                            {{ form_widget(form.Matiere, {'attr': {'class': 'form-control', 'placeholder': 'Enter Subject Name'}}) }}
                        </div>
                  <div class="form-group">
                            {{ form_label(form.Date_Debut) }}
                            {{ form_widget(form.Date_Debut, {'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            {{ form_label(form.Date_Fin) }}
                            {{ form_widget(form.Date_Fin, {'attr': {'class': 'form-control'}}) }}
                        </div>

                           
                     <button type="submit" class="btn btn-info btn-sm">Update</button>
                     
                   
                        {{ form_end(form) }}
                          
                     <div class="d-flex justify-content-between">
                     <a href="{{ path('app_cour_index') }}" class="btn btn-info btn-sm">Back to List</a>
    
                    
    {{ include('cour/_delete_form.html.twig') }}
</div>

              
            
            </div>
        </div>
    </div>
{% endblock %}

templates/cour/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cour index{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/styles.css') }}">
    <style>
        /* Ajoutez vos styles personnalisés ici */
        .add-course-btn {
            position: fixed;
            bottom: 30px;
            right: 30px;
            z-index: 1000;
            width: 100px;
            height: 100px;
            font-size: 24px;
            line-height: 100px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 50%;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            transition: transform 0.3s, box-shadow 0.3s;
            text-align: center;
            text-decoration: none;
        }

        .add-course-btn:hover {
            transform: scale(5.5);
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1);
        }
    </style>
{% endblock %}

{% block body %}
</br>
</br>
<div class="container">
    <h1 class="text-center mt-4 mb-4">Liste des Cours</h1>

    <div class="row mb-4">
        <div class="col-md-6">
            <form method="GET" action="{{ path('app_cour_index') }}">
                <div class="input-group">
                    <input type="text" name="search" class="form-control" placeholder="Matiere">
                    <button type="submit" class="btn btn-primary">Search</button>
                </div>
            </form>
        </div>
        <div class="col-md-6">
            <form method="GET" action="{{ path('app_cour_index') }}">
                <div class="row">
                    <div class="col-md-6">
                        <select name="sort" class="form-control">
                            <option value="date_fin_asc">Trier par date de fin (croissant)</option>
                            <option value="date_fin_desc">Trier par date de fin (décroissant)</option>
                            <option value="nom_asc">Trier par Nom (A-Z)</option>
                            <option value="nom_desc">Trier par Nom (Z-A)</option>
                        </select>
                    </div>
                    <div class="col-md-6">
                        <button type="submit" class="btn btn-primary">Sort</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="row flex-row flex-nowrap overflow-auto">
        {% for cour in cours %}
      
    <div class="col-md-4 mb-4">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">{{ cour.Matiere }}</h5>
            </div>
            <div class="card-body">
                <p class="card-text">Date de Début: {{ cour.DateDebut ? cour.DateDebut|date('d/m/Y H:i') : '' }}</p>
                <p class="card-text">Date de Fin: {{ cour.DateFin ? cour.DateFin|date('d/m/Y H:i') : '' }}</p>
            </div>
            <div class="card-footer d-flex justify-content-between">
                 <a href="{{ path('app_cour_show', {'id': cour.id}) }}" class="custom-btn custom-btn-info btn-sm">Voir</a>
                  <a href="{{ path('app_cour_units', {'id': cour.id}) }}" class="custom-btn custom-btn-warning btn-sm">Unité</a>
                {% if is_granted('ROLE_TEACHER') %}
                    <a href="{{ path('app_cour_edit', {'id': cour.id}) }}" class="custom-btn btn-sm">Modifier</a>
                  
                    {{ include('cour/_delete_form.html.twig') }}
                    <a href="{{ path('app_cour_new') }}" class="add-course-btn">Ajouter un cours</a>
                {% endif %}
            </div>
        </div>
    </div>
{% else %}
    <div class="col">
        <p class="text-center">Aucun cours trouvé.</p>
    </div>
{% endfor %}

      
      
    </div>
  

    
  
</div>
{% endblock %}

templates/cour/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Cour{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset("assets/css/styles.css") }}">
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row justify-content-center mt-5"> {# Ajout de la classe mt-5 pour marge en haut #}
            <div class="col-md-10"> {# Utilisation de col-md-10 au lieu de col-md-8 #}
                <div class="card">
                    <div class="card-header text-center">{{ block('title') }}</div> {# Centrer le texte de l'en-tête #}
                    <div class="card-body">
                        <h2 class="text-center mb-4">Create New Cour</h2>
                        {{ include('Cour/_form.html.twig') }}
                    </div>
                    <div class="card-footer d-flex justify-content-end"> {# Aligner le pied de page à droite #}
                        <a href="{{ path('app_cour_index') }}" class="add-course-btn">Back to List</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/cour/new_unite.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter Unité{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/styles.css') }}">
    <style>
        .label-white {
            color: white; /* Définir la couleur du texte en blanc */
        }
    </style>
{% endblock %}

{% block body %}
    <div class="container">
        <h1>Ajouter Unité pour le Cours {{ cour.Matiere }}</h1>
        {{ form_start(form) }}
        {{ form_row(form.Num_unite) }}
        {{ form_row(form.Titre) }}
        {{ form_row(form.Statut) }}
        {{ form_row(form.Contenu) }}
        {{ form_row(form.id_Cour, {'attr': {'value': cour.id}}) }} {# Champ caché avec l'identifiant du cours #}

        <button type="submit" class="add-course-btn">Ajouter</button>
        <a href="{{ path('app_cour_units', {'id': cour.id}) }}" class="add-course-btn">Annuler</a>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/cour/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails du Cour{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        .card {
            border: 1px solid #ccc;
            border-radius: 5px;
            padding: 10px;
            margin-bottom: 20px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
        .card-header {
            background-color: #f0f0f0;
            padding: 5px;
            border-bottom: 1px solid #ccc;
            border-top-left-radius: 5px;
            border-top-right-radius: 5px;
        }
        .card-body {
            padding: 10px;
        }
    </style>
{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center">Détails du Cour</h1>

    <div class="card">
        <div class="card-header">
            <strong>NAME:</strong> {{ cour.Matiere }}
        </div>
        <div class="card-body">
            <p><strong>Matiere:</strong> {{ cour.Matiere }}</p>
            <p><strong>Date de début:</strong> {{ cour.DateDebut ? cour.DateDebut|date('Y-m-d H:i:s') : 'Non définie' }}</p>
            <p><strong>Date de fin:</strong> {{ cour.DateFin ? cour.DateFin|date('Y-m-d H:i:s') : 'Non définie' }}</p>
        </div>
    </div>

    <div class="text-center mt-3">
        <div class="d-flex justify-content-between">
            <a href="{{ path('app_cour_index') }}" class="add-course-btn">Retour à la liste</a>
            {% if is_granted('ROLE_TEACHER') %}
            <a href="{{ path('app_cour_edit', {'id': cour.id}) }}" class="add-course-btn">Modifier</a>
            {{ include('cour/_delete_form.html.twig') }}
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

templates/cour/units.html.twig
{% extends 'base.html.twig' %}

{% block title %}Unités du Cours {{ cour.Matiere }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        body {
            background-color: #f8f9fa;
            font-family: 'Open Sans', sans-serif;
            color: #333;
        }

        .container {
            max-width: 800px;
            margin: 40px auto;
        }

        .card {
            border: none;
            box-shadow: 0px 4px 15px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px; /* Ajout d'une marge en bas pour séparer les cartes */
            flex: 0 0 auto; /* Empêcher les cartes de s'étirer pour remplir l'espace */
        }

        .card-header {
            background-color: #007bff;
            color: #fff;
            font-weight: bold;
        }

        .card-body {
            padding: 20px; /* Ajout de remplissage pour le corps de la carte */
        }

        .btn-secondary {
            background-color: #6c757d;
            color: #fff;
            border-color: #6c757d;
        }

        .btn-secondary:hover {
            background-color: #5a6268;
            border-color: #545b62;
        }

        .card-container {
            display: flex; /* Utiliser flexbox pour afficher les cartes horizontalement */
            flex-wrap: nowrap; /* Empêcher le retour à la ligne des cartes */
            overflow-x: auto; /* Défilement horizontal */
        }
    </style>
{% endblock %}

{% block body %}

</br>
</br>
</br>
</br>
   <div class="container">
    <h1 class="text-center text-blue">Unités du Cours {{ cour.Matiere }}</h1>

    <div class="row flex-row flex-nowrap overflow-auto card-container"> <!-- Ajout de la classe card-container pour le défilement horizontal -->
        {% for unite in unites %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <div class="card-header">
                       Matière : {{ unite.idCour.matiere }}
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ unite.Titre }}</h5>
                        <p class="card-text"><strong>Statut:</strong> {{ unite.Statut }}</p>
                        <p class="card-text"><strong>Contenu:</strong> {{ unite.Contenu }}</p>
                    </div>
                    <div class="card-footer">
                        <div class="d-flex justify-content-between"> <!-- Utilisation de flexbox pour aligner les boutons -->
                        {% if is_granted('ROLE_TEACHER') %}
                            <a href="{{ path('app_unite_edit', {'id': unite.id}) }}" class="add-course-btn">Edit</a>
                            {{ include('unite/_delete_form.html.twig') }}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="text-center mt-3">
        <a href="{{ path('app_cour_index') }}" class="add-course-btn">Retour à la liste des cours</a>
    </div>
</div>

{% endblock %}